language: csharp
solution: Imgix-CSharp.sln

install:
  - msbuild /t:Restore Imgix-CSharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Imgix-CSharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CryptographyTests/bin/Release/net46/CryptographyTests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Imgix-CSharp-Tests/bin/Release/net46/ImgixClientTests.dll